/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_public = 1,
  anon_sym_type = 2,
  anon_sym_SEMI = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_int = 6,
  anon_sym_float = 7,
  anon_sym_string = 8,
  anon_sym_boolean = 9,
  anon_sym_map = 10,
  anon_sym_null = 11,
  anon_sym_LPAREN_RPAREN = 12,
  anon_sym_PIPE = 13,
  anon_sym_AMP = 14,
  anon_sym_QMARK = 15,
  anon_sym_distinct = 16,
  anon_sym_LBRACK = 17,
  anon_sym_RBRACK = 18,
  anon_sym_STAR = 19,
  anon_sym_COMMA = 20,
  anon_sym_DOT_DOT_DOT = 21,
  anon_sym_LT = 22,
  anon_sym_GT = 23,
  anon_sym_record = 24,
  anon_sym_LBRACE = 25,
  anon_sym_RBRACE = 26,
  anon_sym_LBRACE_PIPE = 27,
  anon_sym_PIPE_RBRACE = 28,
  anon_sym_readonly = 29,
  anon_sym_COLON = 30,
  sym_identifier = 31,
  sym__int_literal = 32,
  sym_source_file = 33,
  sym__module_decl = 34,
  sym_type_decl = 35,
  sym__type_descriptor = 36,
  sym_basic_type = 37,
  sym_nil_literal = 38,
  sym__union_type = 39,
  sym__intersection_type = 40,
  sym__optional_type = 41,
  sym__distinct_type = 42,
  sym__type_reference = 43,
  sym_array_type = 44,
  sym__array_dimension = 45,
  sym__array_length = 46,
  sym_tuple_type = 47,
  sym__tuple_members = 48,
  sym__tuple_rest = 49,
  sym_map_type = 50,
  sym_record_type = 51,
  sym__inclusive_record_type_desc = 52,
  sym__exclusive_record_type_desc = 53,
  sym__field_desc = 54,
  sym__individual_field_desc = 55,
  sym__type_inclusion = 56,
  sym__record_rest = 57,
  sym_qualified_identifier = 58,
  aux_sym_source_file_repeat1 = 59,
  aux_sym_array_type_repeat1 = 60,
  aux_sym__tuple_members_repeat1 = 61,
  aux_sym__inclusive_record_type_desc_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_public] = "public",
  [anon_sym_type] = "type",
  [anon_sym_SEMI] = ";",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_int] = "int",
  [anon_sym_float] = "float",
  [anon_sym_string] = "string",
  [anon_sym_boolean] = "boolean",
  [anon_sym_map] = "map",
  [anon_sym_null] = "null",
  [anon_sym_LPAREN_RPAREN] = "()",
  [anon_sym_PIPE] = "|",
  [anon_sym_AMP] = "&",
  [anon_sym_QMARK] = "\?",
  [anon_sym_distinct] = "distinct",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_STAR] = "*",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT_DOT_DOT] = "...",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_record] = "record",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACE_PIPE] = "{|",
  [anon_sym_PIPE_RBRACE] = "|}",
  [anon_sym_readonly] = "readonly",
  [anon_sym_COLON] = ":",
  [sym_identifier] = "identifier",
  [sym__int_literal] = "_int_literal",
  [sym_source_file] = "source_file",
  [sym__module_decl] = "_module_decl",
  [sym_type_decl] = "type_decl",
  [sym__type_descriptor] = "_type_descriptor",
  [sym_basic_type] = "basic_type",
  [sym_nil_literal] = "nil_literal",
  [sym__union_type] = "_union_type",
  [sym__intersection_type] = "_intersection_type",
  [sym__optional_type] = "_optional_type",
  [sym__distinct_type] = "_distinct_type",
  [sym__type_reference] = "_type_reference",
  [sym_array_type] = "array_type",
  [sym__array_dimension] = "_array_dimension",
  [sym__array_length] = "_array_length",
  [sym_tuple_type] = "tuple_type",
  [sym__tuple_members] = "_tuple_members",
  [sym__tuple_rest] = "_tuple_rest",
  [sym_map_type] = "map_type",
  [sym_record_type] = "record_type",
  [sym__inclusive_record_type_desc] = "_inclusive_record_type_desc",
  [sym__exclusive_record_type_desc] = "_exclusive_record_type_desc",
  [sym__field_desc] = "_field_desc",
  [sym__individual_field_desc] = "_individual_field_desc",
  [sym__type_inclusion] = "_type_inclusion",
  [sym__record_rest] = "_record_rest",
  [sym_qualified_identifier] = "qualified_identifier",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_array_type_repeat1] = "array_type_repeat1",
  [aux_sym__tuple_members_repeat1] = "_tuple_members_repeat1",
  [aux_sym__inclusive_record_type_desc_repeat1] = "_inclusive_record_type_desc_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_type] = anon_sym_type,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_int] = anon_sym_int,
  [anon_sym_float] = anon_sym_float,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_boolean] = anon_sym_boolean,
  [anon_sym_map] = anon_sym_map,
  [anon_sym_null] = anon_sym_null,
  [anon_sym_LPAREN_RPAREN] = anon_sym_LPAREN_RPAREN,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_QMARK] = anon_sym_QMARK,
  [anon_sym_distinct] = anon_sym_distinct,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT_DOT_DOT] = anon_sym_DOT_DOT_DOT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_record] = anon_sym_record,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACE_PIPE] = anon_sym_LBRACE_PIPE,
  [anon_sym_PIPE_RBRACE] = anon_sym_PIPE_RBRACE,
  [anon_sym_readonly] = anon_sym_readonly,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_identifier] = sym_identifier,
  [sym__int_literal] = sym__int_literal,
  [sym_source_file] = sym_source_file,
  [sym__module_decl] = sym__module_decl,
  [sym_type_decl] = sym_type_decl,
  [sym__type_descriptor] = sym__type_descriptor,
  [sym_basic_type] = sym_basic_type,
  [sym_nil_literal] = sym_nil_literal,
  [sym__union_type] = sym__union_type,
  [sym__intersection_type] = sym__intersection_type,
  [sym__optional_type] = sym__optional_type,
  [sym__distinct_type] = sym__distinct_type,
  [sym__type_reference] = sym__type_reference,
  [sym_array_type] = sym_array_type,
  [sym__array_dimension] = sym__array_dimension,
  [sym__array_length] = sym__array_length,
  [sym_tuple_type] = sym_tuple_type,
  [sym__tuple_members] = sym__tuple_members,
  [sym__tuple_rest] = sym__tuple_rest,
  [sym_map_type] = sym_map_type,
  [sym_record_type] = sym_record_type,
  [sym__inclusive_record_type_desc] = sym__inclusive_record_type_desc,
  [sym__exclusive_record_type_desc] = sym__exclusive_record_type_desc,
  [sym__field_desc] = sym__field_desc,
  [sym__individual_field_desc] = sym__individual_field_desc,
  [sym__type_inclusion] = sym__type_inclusion,
  [sym__record_rest] = sym__record_rest,
  [sym_qualified_identifier] = sym_qualified_identifier,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_array_type_repeat1] = aux_sym_array_type_repeat1,
  [aux_sym__tuple_members_repeat1] = aux_sym__tuple_members_repeat1,
  [aux_sym__inclusive_record_type_desc_repeat1] = aux_sym__inclusive_record_type_desc_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_type] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_int] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_float] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_map] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_QMARK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_distinct] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_record] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_readonly] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__int_literal] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__module_decl] = {
    .visible = false,
    .named = true,
  },
  [sym_type_decl] = {
    .visible = true,
    .named = true,
  },
  [sym__type_descriptor] = {
    .visible = false,
    .named = true,
  },
  [sym_basic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_nil_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__union_type] = {
    .visible = false,
    .named = true,
  },
  [sym__intersection_type] = {
    .visible = false,
    .named = true,
  },
  [sym__optional_type] = {
    .visible = false,
    .named = true,
  },
  [sym__distinct_type] = {
    .visible = false,
    .named = true,
  },
  [sym__type_reference] = {
    .visible = false,
    .named = true,
  },
  [sym_array_type] = {
    .visible = true,
    .named = true,
  },
  [sym__array_dimension] = {
    .visible = false,
    .named = true,
  },
  [sym__array_length] = {
    .visible = false,
    .named = true,
  },
  [sym_tuple_type] = {
    .visible = true,
    .named = true,
  },
  [sym__tuple_members] = {
    .visible = false,
    .named = true,
  },
  [sym__tuple_rest] = {
    .visible = false,
    .named = true,
  },
  [sym_map_type] = {
    .visible = true,
    .named = true,
  },
  [sym_record_type] = {
    .visible = true,
    .named = true,
  },
  [sym__inclusive_record_type_desc] = {
    .visible = false,
    .named = true,
  },
  [sym__exclusive_record_type_desc] = {
    .visible = false,
    .named = true,
  },
  [sym__field_desc] = {
    .visible = false,
    .named = true,
  },
  [sym__individual_field_desc] = {
    .visible = false,
    .named = true,
  },
  [sym__type_inclusion] = {
    .visible = false,
    .named = true,
  },
  [sym__record_rest] = {
    .visible = false,
    .named = true,
  },
  [sym_qualified_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_type_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__tuple_members_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__inclusive_record_type_desc_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 19,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 24,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 73,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(54);
      ADVANCE_MAP(
        '&', 75,
        '(', 58,
        ')', 59,
        '*', 81,
        ',', 82,
        '.', 5,
        ':', 94,
        ';', 57,
        '<', 84,
        '>', 85,
        '?', 76,
        '[', 79,
        ']', 80,
        'b', 34,
        'd', 19,
        'f', 25,
        'i', 31,
        'm', 6,
        'n', 50,
        'p', 49,
        'r', 15,
        's', 44,
        't', 52,
        '{', 88,
        '|', 74,
        '}', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '&', 75,
        '(', 58,
        ')', 59,
        ',', 82,
        '.', 5,
        ';', 57,
        '>', 85,
        '?', 76,
        '[', 79,
        ']', 80,
        'b', 120,
        'd', 107,
        'f', 113,
        'i', 118,
        'm', 95,
        'n', 134,
        'r', 104,
        's', 129,
        '|', 73,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '&', 75,
        ')', 59,
        ',', 82,
        '.', 5,
        ':', 94,
        ';', 57,
        '<', 84,
        '>', 85,
        '?', 76,
        '[', 79,
        ']', 80,
        '|', 73,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '(', 58,
        '*', 81,
        ':', 94,
        '[', 79,
        'b', 120,
        'd', 107,
        'f', 113,
        'i', 118,
        'm', 95,
        'n', 134,
        'r', 103,
        's', 129,
        '|', 53,
        '}', 89,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(83);
      END_STATE();
    case 5:
      if (lookahead == '.') ADVANCE(4);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(14);
      if (lookahead == 'c') ADVANCE(36);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 10:
      if (lookahead == 'b') ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(55);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(47);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(86);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(7);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(56);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 18:
      if (lookahead == 'g') ADVANCE(64);
      END_STATE();
    case 19:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(11);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(32);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(51);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(35);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(17);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 30:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 32:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 34:
      if (lookahead == 'o') ADVANCE(37);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(42);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 38:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 39:
      if (lookahead == 'p') ADVANCE(68);
      END_STATE();
    case 40:
      if (lookahead == 'p') ADVANCE(16);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 42:
      if (lookahead == 'r') ADVANCE(13);
      END_STATE();
    case 43:
      if (lookahead == 's') ADVANCE(48);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(60);
      END_STATE();
    case 46:
      if (lookahead == 't') ADVANCE(62);
      END_STATE();
    case 47:
      if (lookahead == 't') ADVANCE(77);
      END_STATE();
    case 48:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 49:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 50:
      if (lookahead == 'u') ADVANCE(28);
      END_STATE();
    case 51:
      if (lookahead == 'y') ADVANCE(92);
      END_STATE();
    case 52:
      if (lookahead == 'y') ADVANCE(40);
      END_STATE();
    case 53:
      if (lookahead == '}') ADVANCE(91);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_type);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      if (lookahead == ')') ADVANCE(72);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_int);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_int);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_float);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_float);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_string);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_string);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_boolean);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_boolean);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_map);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_map);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_null);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_LPAREN_RPAREN);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '}') ADVANCE(91);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(anon_sym_QMARK);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_distinct);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_distinct);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(anon_sym_DOT_DOT_DOT);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_record);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_record);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '|') ADVANCE(90);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_LBRACE_PIPE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_PIPE_RBRACE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_readonly);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_readonly);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(125);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(102);
      if (lookahead == 'c') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(131);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(117);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(122);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'c') ADVANCE(132);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(124);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(96);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(99);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(98);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'g') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(128);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(115);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'i') ADVANCE(116);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(135);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(105);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(121);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(110);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(106);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(100);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(130);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(111);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(123);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(97);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(127);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(112);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(108);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(126);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(109);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(114);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'y') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(136);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym__int_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 3},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 2},
  [46] = {.lex_state = 2},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 3},
  [78] = {.lex_state = 2},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 3},
  [84] = {.lex_state = 3},
  [85] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_type] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_int] = ACTIONS(1),
    [anon_sym_float] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [anon_sym_map] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_QMARK] = ACTIONS(1),
    [anon_sym_distinct] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT_DOT_DOT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_record] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_PIPE] = ACTIONS(1),
    [anon_sym_PIPE_RBRACE] = ACTIONS(1),
    [anon_sym_readonly] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym__int_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(74),
    [sym__module_decl] = STATE(59),
    [sym_type_decl] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(59),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_public] = ACTIONS(5),
    [anon_sym_type] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__type_descriptor] = STATE(52),
    [sym_basic_type] = STATE(52),
    [sym_nil_literal] = STATE(45),
    [sym__union_type] = STATE(52),
    [sym__intersection_type] = STATE(52),
    [sym__optional_type] = STATE(52),
    [sym__distinct_type] = STATE(52),
    [sym__type_reference] = STATE(52),
    [sym_array_type] = STATE(52),
    [sym_tuple_type] = STATE(52),
    [sym_map_type] = STATE(52),
    [sym_record_type] = STATE(52),
    [sym__inclusive_record_type_desc] = STATE(38),
    [sym__exclusive_record_type_desc] = STATE(38),
    [sym__field_desc] = STATE(2),
    [sym__individual_field_desc] = STATE(2),
    [sym__type_inclusion] = STATE(2),
    [sym_qualified_identifier] = STATE(52),
    [aux_sym__inclusive_record_type_desc_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(9),
    [anon_sym_int] = ACTIONS(12),
    [anon_sym_float] = ACTIONS(12),
    [anon_sym_string] = ACTIONS(12),
    [anon_sym_boolean] = ACTIONS(12),
    [anon_sym_map] = ACTIONS(15),
    [anon_sym_null] = ACTIONS(18),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(21),
    [anon_sym_distinct] = ACTIONS(24),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_STAR] = ACTIONS(30),
    [anon_sym_record] = ACTIONS(33),
    [anon_sym_RBRACE] = ACTIONS(36),
    [anon_sym_PIPE_RBRACE] = ACTIONS(36),
    [anon_sym_readonly] = ACTIONS(38),
    [sym_identifier] = ACTIONS(41),
  },
  [STATE(3)] = {
    [sym__type_descriptor] = STATE(50),
    [sym_basic_type] = STATE(50),
    [sym_nil_literal] = STATE(45),
    [sym__union_type] = STATE(50),
    [sym__intersection_type] = STATE(50),
    [sym__optional_type] = STATE(50),
    [sym__distinct_type] = STATE(50),
    [sym__type_reference] = STATE(50),
    [sym_array_type] = STATE(50),
    [sym_tuple_type] = STATE(50),
    [sym_map_type] = STATE(50),
    [sym_record_type] = STATE(50),
    [sym__inclusive_record_type_desc] = STATE(38),
    [sym__exclusive_record_type_desc] = STATE(38),
    [sym__field_desc] = STATE(4),
    [sym__individual_field_desc] = STATE(4),
    [sym__type_inclusion] = STATE(4),
    [sym__record_rest] = STATE(83),
    [sym_qualified_identifier] = STATE(50),
    [aux_sym__inclusive_record_type_desc_repeat1] = STATE(4),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_int] = ACTIONS(46),
    [anon_sym_float] = ACTIONS(46),
    [anon_sym_string] = ACTIONS(46),
    [anon_sym_boolean] = ACTIONS(46),
    [anon_sym_map] = ACTIONS(48),
    [anon_sym_null] = ACTIONS(50),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(52),
    [anon_sym_distinct] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(58),
    [anon_sym_record] = ACTIONS(60),
    [anon_sym_PIPE_RBRACE] = ACTIONS(62),
    [anon_sym_readonly] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
  },
  [STATE(4)] = {
    [sym__type_descriptor] = STATE(50),
    [sym_basic_type] = STATE(50),
    [sym_nil_literal] = STATE(45),
    [sym__union_type] = STATE(50),
    [sym__intersection_type] = STATE(50),
    [sym__optional_type] = STATE(50),
    [sym__distinct_type] = STATE(50),
    [sym__type_reference] = STATE(50),
    [sym_array_type] = STATE(50),
    [sym_tuple_type] = STATE(50),
    [sym_map_type] = STATE(50),
    [sym_record_type] = STATE(50),
    [sym__inclusive_record_type_desc] = STATE(38),
    [sym__exclusive_record_type_desc] = STATE(38),
    [sym__field_desc] = STATE(2),
    [sym__individual_field_desc] = STATE(2),
    [sym__type_inclusion] = STATE(2),
    [sym__record_rest] = STATE(84),
    [sym_qualified_identifier] = STATE(50),
    [aux_sym__inclusive_record_type_desc_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_int] = ACTIONS(46),
    [anon_sym_float] = ACTIONS(46),
    [anon_sym_string] = ACTIONS(46),
    [anon_sym_boolean] = ACTIONS(46),
    [anon_sym_map] = ACTIONS(48),
    [anon_sym_null] = ACTIONS(50),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(52),
    [anon_sym_distinct] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(58),
    [anon_sym_record] = ACTIONS(60),
    [anon_sym_PIPE_RBRACE] = ACTIONS(68),
    [anon_sym_readonly] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
  },
  [STATE(5)] = {
    [sym__type_descriptor] = STATE(52),
    [sym_basic_type] = STATE(52),
    [sym_nil_literal] = STATE(45),
    [sym__union_type] = STATE(52),
    [sym__intersection_type] = STATE(52),
    [sym__optional_type] = STATE(52),
    [sym__distinct_type] = STATE(52),
    [sym__type_reference] = STATE(52),
    [sym_array_type] = STATE(52),
    [sym_tuple_type] = STATE(52),
    [sym_map_type] = STATE(52),
    [sym_record_type] = STATE(52),
    [sym__inclusive_record_type_desc] = STATE(38),
    [sym__exclusive_record_type_desc] = STATE(38),
    [sym__field_desc] = STATE(6),
    [sym__individual_field_desc] = STATE(6),
    [sym__type_inclusion] = STATE(6),
    [sym_qualified_identifier] = STATE(52),
    [aux_sym__inclusive_record_type_desc_repeat1] = STATE(6),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_int] = ACTIONS(46),
    [anon_sym_float] = ACTIONS(46),
    [anon_sym_string] = ACTIONS(46),
    [anon_sym_boolean] = ACTIONS(46),
    [anon_sym_map] = ACTIONS(48),
    [anon_sym_null] = ACTIONS(50),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(52),
    [anon_sym_distinct] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(58),
    [anon_sym_record] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(70),
    [anon_sym_readonly] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
  },
  [STATE(6)] = {
    [sym__type_descriptor] = STATE(52),
    [sym_basic_type] = STATE(52),
    [sym_nil_literal] = STATE(45),
    [sym__union_type] = STATE(52),
    [sym__intersection_type] = STATE(52),
    [sym__optional_type] = STATE(52),
    [sym__distinct_type] = STATE(52),
    [sym__type_reference] = STATE(52),
    [sym_array_type] = STATE(52),
    [sym_tuple_type] = STATE(52),
    [sym_map_type] = STATE(52),
    [sym_record_type] = STATE(52),
    [sym__inclusive_record_type_desc] = STATE(38),
    [sym__exclusive_record_type_desc] = STATE(38),
    [sym__field_desc] = STATE(2),
    [sym__individual_field_desc] = STATE(2),
    [sym__type_inclusion] = STATE(2),
    [sym_qualified_identifier] = STATE(52),
    [aux_sym__inclusive_record_type_desc_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(44),
    [anon_sym_int] = ACTIONS(46),
    [anon_sym_float] = ACTIONS(46),
    [anon_sym_string] = ACTIONS(46),
    [anon_sym_boolean] = ACTIONS(46),
    [anon_sym_map] = ACTIONS(48),
    [anon_sym_null] = ACTIONS(50),
    [anon_sym_LPAREN_RPAREN] = ACTIONS(52),
    [anon_sym_distinct] = ACTIONS(54),
    [anon_sym_LBRACK] = ACTIONS(56),
    [anon_sym_STAR] = ACTIONS(58),
    [anon_sym_record] = ACTIONS(60),
    [anon_sym_RBRACE] = ACTIONS(72),
    [anon_sym_readonly] = ACTIONS(64),
    [sym_identifier] = ACTIONS(66),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    STATE(71), 2,
      sym__tuple_members,
      sym__tuple_rest,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(48), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [56] = 13,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(79), 1,
      sym__tuple_rest,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(49), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [111] = 13,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(72), 1,
      sym__tuple_rest,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(49), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [166] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(58), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [218] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(56), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [270] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(30), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [322] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(31), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [374] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(54), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [426] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(29), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [478] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(55), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [530] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(51), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [582] = 12,
    ACTIONS(44), 1,
      anon_sym_LPAREN,
    ACTIONS(48), 1,
      anon_sym_map,
    ACTIONS(50), 1,
      anon_sym_null,
    ACTIONS(52), 1,
      anon_sym_LPAREN_RPAREN,
    ACTIONS(54), 1,
      anon_sym_distinct,
    ACTIONS(56), 1,
      anon_sym_LBRACK,
    ACTIONS(60), 1,
      anon_sym_record,
    ACTIONS(66), 1,
      sym_identifier,
    STATE(45), 1,
      sym_nil_literal,
    STATE(38), 2,
      sym__inclusive_record_type_desc,
      sym__exclusive_record_type_desc,
    ACTIONS(46), 4,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
    STATE(57), 12,
      sym__type_descriptor,
      sym_basic_type,
      sym__union_type,
      sym__intersection_type,
      sym__optional_type,
      sym__distinct_type,
      sym__type_reference,
      sym_array_type,
      sym_tuple_type,
      sym_map_type,
      sym_record_type,
      sym_qualified_identifier,
  [634] = 3,
    ACTIONS(78), 1,
      anon_sym_COLON,
    ACTIONS(76), 5,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym_RBRACE,
      anon_sym_PIPE_RBRACE,
    ACTIONS(74), 11,
      anon_sym_LPAREN,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      anon_sym_map,
      anon_sym_null,
      anon_sym_distinct,
      anon_sym_record,
      anon_sym_readonly,
      sym_identifier,
  [658] = 2,
    ACTIONS(82), 5,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym_RBRACE,
      anon_sym_PIPE_RBRACE,
    ACTIONS(80), 11,
      anon_sym_LPAREN,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      anon_sym_map,
      anon_sym_null,
      anon_sym_distinct,
      anon_sym_record,
      anon_sym_readonly,
      sym_identifier,
  [679] = 2,
    ACTIONS(86), 5,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym_RBRACE,
      anon_sym_PIPE_RBRACE,
    ACTIONS(84), 11,
      anon_sym_LPAREN,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      anon_sym_map,
      anon_sym_null,
      anon_sym_distinct,
      anon_sym_record,
      anon_sym_readonly,
      sym_identifier,
  [700] = 2,
    ACTIONS(90), 5,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym_RBRACE,
      anon_sym_PIPE_RBRACE,
    ACTIONS(88), 11,
      anon_sym_LPAREN,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      anon_sym_map,
      anon_sym_null,
      anon_sym_distinct,
      anon_sym_record,
      anon_sym_readonly,
      sym_identifier,
  [721] = 2,
    ACTIONS(94), 5,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym_RBRACE,
      anon_sym_PIPE_RBRACE,
    ACTIONS(92), 11,
      anon_sym_LPAREN,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      anon_sym_map,
      anon_sym_null,
      anon_sym_distinct,
      anon_sym_record,
      anon_sym_readonly,
      sym_identifier,
  [742] = 2,
    ACTIONS(98), 5,
      anon_sym_LPAREN_RPAREN,
      anon_sym_LBRACK,
      anon_sym_STAR,
      anon_sym_RBRACE,
      anon_sym_PIPE_RBRACE,
    ACTIONS(96), 11,
      anon_sym_LPAREN,
      anon_sym_int,
      anon_sym_float,
      anon_sym_string,
      anon_sym_boolean,
      anon_sym_map,
      anon_sym_null,
      anon_sym_distinct,
      anon_sym_record,
      anon_sym_readonly,
      sym_identifier,
  [763] = 2,
    STATE(27), 2,
      sym__array_dimension,
      aux_sym_array_type_repeat1,
    ACTIONS(100), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [781] = 3,
    ACTIONS(104), 1,
      anon_sym_LBRACK,
    STATE(26), 2,
      sym__array_dimension,
      aux_sym_array_type_repeat1,
    ACTIONS(102), 10,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [801] = 2,
    STATE(26), 2,
      sym__array_dimension,
      aux_sym_array_type_repeat1,
    ACTIONS(107), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [819] = 2,
    ACTIONS(109), 1,
      anon_sym_COLON,
    ACTIONS(76), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [836] = 2,
    STATE(25), 1,
      sym__array_dimension,
    ACTIONS(111), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [853] = 2,
    STATE(25), 1,
      sym__array_dimension,
    ACTIONS(113), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [870] = 2,
    STATE(25), 1,
      sym__array_dimension,
    ACTIONS(115), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [887] = 2,
    ACTIONS(119), 1,
      anon_sym_LT,
    ACTIONS(117), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [904] = 1,
    ACTIONS(121), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [918] = 1,
    ACTIONS(123), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [932] = 1,
    ACTIONS(98), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [946] = 1,
    ACTIONS(125), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [960] = 1,
    ACTIONS(127), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [974] = 1,
    ACTIONS(129), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [988] = 1,
    ACTIONS(131), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1002] = 1,
    ACTIONS(133), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1016] = 1,
    ACTIONS(135), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1030] = 1,
    ACTIONS(137), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1044] = 1,
    ACTIONS(139), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1058] = 1,
    ACTIONS(141), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1072] = 1,
    ACTIONS(117), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1086] = 1,
    ACTIONS(143), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1100] = 1,
    ACTIONS(145), 11,
      anon_sym_SEMI,
      anon_sym_RPAREN,
      anon_sym_PIPE,
      anon_sym_AMP,
      anon_sym_QMARK,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT_DOT_DOT,
      anon_sym_GT,
      sym_identifier,
  [1114] = 9,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(155), 1,
      anon_sym_RBRACK,
    ACTIONS(157), 1,
      anon_sym_COMMA,
    ACTIONS(159), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(25), 1,
      sym__array_dimension,
    STATE(64), 1,
      aux_sym__tuple_members_repeat1,
  [1142] = 7,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(159), 1,
      anon_sym_DOT_DOT_DOT,
    STATE(25), 1,
      sym__array_dimension,
    ACTIONS(161), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1165] = 7,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(163), 1,
      anon_sym_DOT_DOT_DOT,
    ACTIONS(165), 1,
      sym_identifier,
    STATE(25), 1,
      sym__array_dimension,
  [1187] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    STATE(25), 1,
      sym__array_dimension,
    ACTIONS(161), 2,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [1207] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(165), 1,
      sym_identifier,
    STATE(25), 1,
      sym__array_dimension,
  [1226] = 4,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 1,
      anon_sym_public,
    ACTIONS(172), 1,
      anon_sym_type,
    STATE(53), 3,
      sym__module_decl,
      sym_type_decl,
      aux_sym_source_file_repeat1,
  [1241] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(175), 1,
      anon_sym_SEMI,
    STATE(25), 1,
      sym__array_dimension,
  [1260] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(177), 1,
      anon_sym_GT,
    STATE(25), 1,
      sym__array_dimension,
  [1279] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(179), 1,
      anon_sym_SEMI,
    STATE(25), 1,
      sym__array_dimension,
  [1298] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(181), 1,
      anon_sym_RPAREN,
    STATE(25), 1,
      sym__array_dimension,
  [1317] = 6,
    ACTIONS(147), 1,
      anon_sym_PIPE,
    ACTIONS(149), 1,
      anon_sym_AMP,
    ACTIONS(151), 1,
      anon_sym_QMARK,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    ACTIONS(183), 1,
      sym_identifier,
    STATE(25), 1,
      sym__array_dimension,
  [1336] = 4,
    ACTIONS(5), 1,
      anon_sym_public,
    ACTIONS(7), 1,
      anon_sym_type,
    ACTIONS(185), 1,
      ts_builtin_sym_end,
    STATE(53), 3,
      sym__module_decl,
      sym_type_decl,
      aux_sym_source_file_repeat1,
  [1351] = 3,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      sym__array_length,
    ACTIONS(189), 2,
      anon_sym_STAR,
      sym__int_literal,
  [1362] = 1,
    ACTIONS(191), 3,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_type,
  [1368] = 1,
    ACTIONS(193), 3,
      ts_builtin_sym_end,
      anon_sym_public,
      anon_sym_type,
  [1374] = 2,
    ACTIONS(195), 1,
      sym_identifier,
    STATE(23), 2,
      sym__type_reference,
      sym_qualified_identifier,
  [1382] = 3,
    ACTIONS(197), 1,
      anon_sym_RBRACK,
    ACTIONS(199), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym__tuple_members_repeat1,
  [1392] = 3,
    ACTIONS(161), 1,
      anon_sym_RBRACK,
    ACTIONS(201), 1,
      anon_sym_COMMA,
    STATE(65), 1,
      aux_sym__tuple_members_repeat1,
  [1402] = 2,
    ACTIONS(204), 1,
      anon_sym_SEMI,
    ACTIONS(206), 1,
      anon_sym_QMARK,
  [1409] = 2,
    ACTIONS(208), 1,
      anon_sym_LBRACE,
    ACTIONS(210), 1,
      anon_sym_LBRACE_PIPE,
  [1416] = 2,
    ACTIONS(212), 1,
      anon_sym_SEMI,
    ACTIONS(214), 1,
      anon_sym_QMARK,
  [1423] = 1,
    ACTIONS(204), 1,
      anon_sym_SEMI,
  [1427] = 1,
    ACTIONS(216), 1,
      anon_sym_RBRACK,
  [1431] = 1,
    ACTIONS(218), 1,
      anon_sym_RBRACK,
  [1435] = 1,
    ACTIONS(220), 1,
      anon_sym_RBRACK,
  [1439] = 1,
    ACTIONS(222), 1,
      sym_identifier,
  [1443] = 1,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
  [1447] = 1,
    ACTIONS(226), 1,
      anon_sym_RBRACK,
  [1451] = 1,
    ACTIONS(228), 1,
      anon_sym_type,
  [1455] = 1,
    ACTIONS(230), 1,
      anon_sym_PIPE_RBRACE,
  [1459] = 1,
    ACTIONS(232), 1,
      sym_identifier,
  [1463] = 1,
    ACTIONS(234), 1,
      anon_sym_RBRACK,
  [1467] = 1,
    ACTIONS(236), 1,
      anon_sym_SEMI,
  [1471] = 1,
    ACTIONS(238), 1,
      anon_sym_SEMI,
  [1475] = 1,
    ACTIONS(240), 1,
      sym_identifier,
  [1479] = 1,
    ACTIONS(68), 1,
      anon_sym_PIPE_RBRACE,
  [1483] = 1,
    ACTIONS(242), 1,
      anon_sym_PIPE_RBRACE,
  [1487] = 1,
    ACTIONS(244), 1,
      sym_identifier,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 56,
  [SMALL_STATE(9)] = 111,
  [SMALL_STATE(10)] = 166,
  [SMALL_STATE(11)] = 218,
  [SMALL_STATE(12)] = 270,
  [SMALL_STATE(13)] = 322,
  [SMALL_STATE(14)] = 374,
  [SMALL_STATE(15)] = 426,
  [SMALL_STATE(16)] = 478,
  [SMALL_STATE(17)] = 530,
  [SMALL_STATE(18)] = 582,
  [SMALL_STATE(19)] = 634,
  [SMALL_STATE(20)] = 658,
  [SMALL_STATE(21)] = 679,
  [SMALL_STATE(22)] = 700,
  [SMALL_STATE(23)] = 721,
  [SMALL_STATE(24)] = 742,
  [SMALL_STATE(25)] = 763,
  [SMALL_STATE(26)] = 781,
  [SMALL_STATE(27)] = 801,
  [SMALL_STATE(28)] = 819,
  [SMALL_STATE(29)] = 836,
  [SMALL_STATE(30)] = 853,
  [SMALL_STATE(31)] = 870,
  [SMALL_STATE(32)] = 887,
  [SMALL_STATE(33)] = 904,
  [SMALL_STATE(34)] = 918,
  [SMALL_STATE(35)] = 932,
  [SMALL_STATE(36)] = 946,
  [SMALL_STATE(37)] = 960,
  [SMALL_STATE(38)] = 974,
  [SMALL_STATE(39)] = 988,
  [SMALL_STATE(40)] = 1002,
  [SMALL_STATE(41)] = 1016,
  [SMALL_STATE(42)] = 1030,
  [SMALL_STATE(43)] = 1044,
  [SMALL_STATE(44)] = 1058,
  [SMALL_STATE(45)] = 1072,
  [SMALL_STATE(46)] = 1086,
  [SMALL_STATE(47)] = 1100,
  [SMALL_STATE(48)] = 1114,
  [SMALL_STATE(49)] = 1142,
  [SMALL_STATE(50)] = 1165,
  [SMALL_STATE(51)] = 1187,
  [SMALL_STATE(52)] = 1207,
  [SMALL_STATE(53)] = 1226,
  [SMALL_STATE(54)] = 1241,
  [SMALL_STATE(55)] = 1260,
  [SMALL_STATE(56)] = 1279,
  [SMALL_STATE(57)] = 1298,
  [SMALL_STATE(58)] = 1317,
  [SMALL_STATE(59)] = 1336,
  [SMALL_STATE(60)] = 1351,
  [SMALL_STATE(61)] = 1362,
  [SMALL_STATE(62)] = 1368,
  [SMALL_STATE(63)] = 1374,
  [SMALL_STATE(64)] = 1382,
  [SMALL_STATE(65)] = 1392,
  [SMALL_STATE(66)] = 1402,
  [SMALL_STATE(67)] = 1409,
  [SMALL_STATE(68)] = 1416,
  [SMALL_STATE(69)] = 1423,
  [SMALL_STATE(70)] = 1427,
  [SMALL_STATE(71)] = 1431,
  [SMALL_STATE(72)] = 1435,
  [SMALL_STATE(73)] = 1439,
  [SMALL_STATE(74)] = 1443,
  [SMALL_STATE(75)] = 1447,
  [SMALL_STATE(76)] = 1451,
  [SMALL_STATE(77)] = 1455,
  [SMALL_STATE(78)] = 1459,
  [SMALL_STATE(79)] = 1463,
  [SMALL_STATE(80)] = 1467,
  [SMALL_STATE(81)] = 1471,
  [SMALL_STATE(82)] = 1475,
  [SMALL_STATE(83)] = 1479,
  [SMALL_STATE(84)] = 1483,
  [SMALL_STATE(85)] = 1487,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [9] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [12] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(67),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__inclusive_record_type_desc_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [46] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(67),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_reference, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_reference, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__individual_field_desc, 4, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__individual_field_desc, 4, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__individual_field_desc, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__individual_field_desc, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__individual_field_desc, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__individual_field_desc, 5, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__type_inclusion, 2, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_inclusion, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_qualified_identifier, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_qualified_identifier, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2, 0, 0),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_type_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_type, 3, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__distinct_type, 2, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__union_type, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__intersection_type, 3, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_basic_type, 1, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exclusive_record_type_desc, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type_descriptor, 3, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_type, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inclusive_record_type_desc, 3, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record_type, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_dimension, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map_type, 4, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exclusive_record_type_desc, 4, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__exclusive_record_type_desc, 5, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_dimension, 3, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__inclusive_record_type_desc, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__optional_type, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_nil_literal, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tuple_members, 1, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__tuple_members_repeat1, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [169] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(76),
  [172] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 5, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_decl, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tuple_members, 2, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [201] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__tuple_members_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [208] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tuple_members, 4, 0, 0),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [224] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tuple_rest, 2, 0, 0),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__record_rest, 3, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tuple_members, 3, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tree_sitter_ballerina(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "tree_sitter_ballerina",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 2,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
